### ISSUE TITLE
Seperate Signup and Login Page / Form

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#108]
This leads to confusion of users who mistype their emails.

**Comment by funtonia** [comment]
Would like to work on this, do you already have more info for the issue? :) 
It would especially be good to know how the seperation should happen (two different buttons/links // show sign up as default and create a "...or login" link below // ...) in order start implementing.

**Comment by Maurice22** [comment]
We would imagine the following user flow:

User lands on sign**in** page (i.e. because selected action requires auth). User can enter email and PW and can click on a **Login** button. Instead of doing an automatic signup here, we would only check for the validity of the provided credentials. If the credentials are wrong, the user will be displayed an error message.

Next to the login button we also have a **Signup** button. If the user clicks on the signup button, he will be redirected to a sign**up** page which in the first iteration would pretty much look like the signin page but with adapted text. There, the user will also enter email and PW and when the user clicks on Register, we will register a new account and send out the verification email.

It is important, that the current functionality with the redirects, etc. will stay intact, even if we would have a useraction -> redirect signin -> redirect signup case.

**Comment by Maurice22** [comment]
@funtonia , I will take up this issue as we figured this is a high priority issues where we also need to be in close contact to our designers. Thank you anyways for your interest in this issue and helping our project ❤️ .
