### ISSUE TITLE
Create easy-to-use dummy firebase environment

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#114]
*Steps*
- [x] Env variables
- [x] Readme
- [x] Track progress related issues & prs

**Comment by tgraupne** [comment]
We added env variables to configure firebase here: jagaSto@24e87ab689919f0327aca4043c948a59cb3913f5

**Comment by tgraupne** [comment]
Hey Team, is something missing in my remarks on contributions? https://github.com/kenodressel/quarantine-hero/commit/5da21143c68087187ec8e59db01dde43c49eafaa
@Maurice22 @florianschmidt1994 @kenodressel

**Comment by florianschmidt1994** [comment]
We need to think about security rules and how they are mirrored from prod to staging. I don't know if / how we should remarks to the readme, just something I've just thought of

**Comment by tgraupne** [comment]
> We need to think about security rules and how they are mirrored from prod to staging. I don't know if / how we should remarks to the readme, just something I've just thought of

If the stage environment is something contributors only use for frontend testing, we could replicate security rules from production because we would not expose them.

This aligns with my understanding of the stage-environment as an internal tool. Contributors to the backend project should setup their own firebase instance to test and develop their cloud functions.

**Comment by florianschmidt1994** [comment]
True. Are we doing this manually right now? In any case, I don't think we need to mention them in the docs if we go with the model you've mentioned

**Comment by tgraupne** [comment]
> True. Are we doing this manually right now?

Yes.

**Comment by tgraupne** [comment]
#132
