### ISSUE TITLE
Layout issue with flagged post

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#136]
![image](https://user-images.githubusercontent.com/6798306/77370828-00734b80-6d62-11ea-8376-dae6c7eb1edb.png)

**Comment by jagaSto** [comment]
the issue is unrelated to the reporting state of the posting (reported/not reported). Instead, the issue is that the description is too long, in those cases where we show the full address instead of only the postal code, see screenshot below

![Screenshot 2020-03-24 at 11 20 10](https://user-images.githubusercontent.com/20641332/77414582-92f70780-6dc1-11ea-8401-10944760403e.png)
