### ISSUE TITLE
Fix internationalization for date-fns

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#265]
The usage of date-ins formatDistance function produces weird grammar mistakes in German. It has to be investigated how this can be fixed.

![Screenshot](https://user-images.githubusercontent.com/20804369/80593547-b85edd00-8a21-11ea-9c05-f2bc4b048259.jpg)

**Comment by jakob-ed** [comment]
I investigated this a bit just now. The issue seems to be that the "vor" comes from the i18n file and not from `date-fns`. Therefore, the grammatical case from the text generated by `date-fns` doesn't match the grammatical case that "vor" requires in German. 

Long story short, there's a flag for `formatDistance` called `addSuffix` that changes the text and makes `date-fns` output the "vor" along with the text in the right grammatical case. See 3rd example here: https://date-fns.org/v2.0.0-alpha.7/docs/formatDistance#examples

I can take this issue if you'd like @Maurice22

**Comment by Maurice22** [comment]
Nice! Sure, go ahead and I will assign you the issue. While you are at it, there is also a TODO for using the “right” internationalization for the function as it is currently hard coded to ‘de’... If you are interested in it, you could possibly fix this as well, however I don’t want to assign you anything you are not interested in ✌🏻
If you want to take care about the internationalization language as well, I am sure you can get an array of preferred internationalization languages from the i18next library. An example can be found in #248 where I use it in the useCms hook.

**Comment by jakob-ed** [comment]
Hm I would do it but I'm not quite sure how to solve it best. `date-fns` expects one of its `locale` objects while `i18next.language` only provides a language code String. So we would have to do some mapping from String to `locale` and if possible maybe do this in a central location. `date-fns` even [recommends this](https://date-fns.org/v2.12.0/docs/I18n#usage). Any ideas where a good place for this could be?

I would propose to first solve only the grammatical problems first.

**Comment by Maurice22** [comment]
I hacked together the following function. What do you think about it?
```
import * as locales from 'date-fns/locale';
import { enUS } from 'date-fns/locale';
import i18next from 'i18next';

const { languages } = i18next;
const getLocale = (l) => {
  for (let i = 0; i < l.length; i += 1) {
    const locale = locales[l[i].replace('-', '')]
    if (locale) {
      return locale;
    }
  }
  return enUS;
};
```
