### ISSUE TITLE
Add reporting feature for malicious posts

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#27]

**Comment by jagaSto** [comment]
How exactly should this look like? A little button somewhere in the corner of the entry where people can report the post? What should happen on click? An email to someone with the administrative power to remove the entry, if it turns out to be spam?
E.g.

![Screenshot 2020-03-18 at 21 55 01](https://user-images.githubusercontent.com/20641332/77006858-7a22c800-6963-11ea-92a1-6b6a216f3f72.png)

**Comment by DaAngus** [comment]
Conspiracy posts are most of the times copy&paste and contain words unlikely used in a regular request.
Posts containing such words should be marked for review first.
If you need help for grunt work let me know

**Comment by kenodressel** [comment]
@jagaSto 
The button looks good. I would store this in the firebase backend. This could be done in a new collection (easier for write access).

**Comment by jagaSto** [comment]
Cool, will try to implement it like this then and let you know in case I have questions :)

**Comment by kenodressel** [comment]
Sounds Good!

**Comment by jagaSto** [comment]
First question: what exactly should happen once the user clicks on "Melden"?  Should it 

a) show a dialog asking the user to state what's wrong with the report? 

Or 

b) simply report the entry directly? 

With a) we get context and users cannot simply spam-report every entry, but b) is less effort ( no need for a dialog window)

**Comment by kenodressel** [comment]
Simply report it. For now we wont act on it anyways. Its just to get a feeling for the numbers.

**Comment by Maurice22** [comment]
I vote for having at least a confirmation dialog (not necessarily with reason for now). I think this would reduce potential abuse (by lowing malicious people down)
