### ISSUE TITLE
Don't allow single-use emails on signup

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#36]
Blacklist some well-known "throw-away-email" domain for user registration.

Reference:
https://github.com/johnduhart/throwaway-email-blacklist/blob/master/domains.txt
https://www.internet-neukunden.de/2009/02/22/liste-mit-57-anbieter-von-wegwerf-emails-antispam/
https://videonerd.de/wegwerf-e-mail-adressen/

**Comment by wiredancer** [comment]
I can see valid use cases for single-use email addresses here, especially since the email address used is not hidden to the corresponding party. I would use a throw-away address just for the first contact, and then exchange phone numbers etc. as soon as I trust the other person is not a bot or something.

**Comment by kenodressel** [comment]
This is a tight balance between spam protection and privacy and since the majority of the users here seems to be honest and the number of responses to a single person is rather low (usually ~5) there are easier ways to gather emails than insert an help request on our plattform.

**Comment by funtonia** [comment]
So does this mean the issue is still valid and open, @kenodressel ? Would have a look at it tonight.

**Comment by Maurice22** [comment]
@funtonia This is still a task, help is highly appreciated!

**Comment by funtonia** [comment]
I implemented a check against the static DEM-list mentioned in the issues' description. However, we must keep in mind that this will never filter all DEMs as new ones are created every day and there is no framework offering a reliable and constantly updated filtering (yet).

What should happen if a user enters a DEM? The easiest way would be to simply change the feedback text which is shown when users try to submit a non-valid mail-address ("Bitte geben Sie eine E-Mail-Adresse ein." could be changed to sth like "Bitte geben Sie eine valide E-Mail-Adresse ein, die keine Wegwerf-Adresse ist.") and could maybe do the trick **for now**. Wdyt?

From a UXD point of view, I would generally suggest to check for correct user input **before** sending it to the server and to disable the submit-button until a valid mail-address and zip-code are entered. Will open a new issue for this in which we can discuss if this would be a wanted feature or not.

**Comment by Maurice22** [comment]
For a first implementation, I would suggest the frontend will check the email and if it matches one of the blacklist, we will disable the submission of the form. Can you please check how this can be handled using the current HTML5 forms? Also with regards to the custom error/validation message?

**Comment by funtonia** [comment]
Sure, sounds good. I wasn't able to find the error message within the frontend code & thus think that it might come from the backend? Right now, the submission is disabled if any of the inputs is invalid, but no message is shown (because I can't figure out how to) - help would be very much appreciated!

**Comment by Maurice22** [comment]
@funtonia Please check out HTML5 forms validation and the `required` attribute. The error messages right now are created by the browser. We might need to add custom error messages for this.

**Comment by funtonia** [comment]
We have two possibilities here: 

1. Disable the submit-button and implement a custom error message view (this could be a nice approach: https://www.telerik.com/blogs/up-and-running-with-react-form-validation)
2. Do not disable the submit-button, but show a custom error message for DEMs (after clicking the submit-button)

If we go with 1), I would suggest making that a new issue, because it goes in the direction of a redesign (should probably be done for all input fields - again: talking from a UXD point of view).

**Comment by Maurice22** [comment]
Would go with approach 2 for now. Have you checked whether this is possible using HTML5 forms and validation?

**Comment by funtonia** [comment]
Yes, the implementation of it is all done with HTML5 form input validation! All I need to complete the issue is the error message string that should be shown - everything else is ready.

**Comment by Maurice22** [comment]
I would vote for "Bitte keine Wegwerf-Emailadresse verwenden". Opinions?
@florianschmidt1994 @tgraupne @kenodressel

**Comment by tgraupne** [comment]
> I would vote for "Bitte keine Wegwerf-Emailadresse verwenden". Opinions?
> @florianschmidt1994 @tgraupne @kenodressel

I general, I think this is an important issue and I am very happy that @funtonia is offering help here.

I regards to the error message: 
> Bitte keine Wegwerf-Emailadresse verwenden.
I ok for now. I do have the feeling, that there could be a better wording, but for now it is ok.

However, I was wondering if we should include maybe one or two sentences about why we exclude DEMs. 🤔

**Comment by Maurice22** [comment]
Hey @funtonia , thanks again for contributing on this. Just create a pull request as soon as you think you have finished this issue, thanks :)
