### ISSUE TITLE
Reactivate Google GeoLocation API

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#56]
- [ ] Migrate Database (plz --> geolocations)
- [ ] Verify that the website still works when we flip the feature flag
- [ ] Verify that the firebase functions still works when we flip the feature flag
- [ ] make the repo backwards compatible so that we can always go back to plz with out migration

The backwards compatibility is enforce by only allowing users to input a plz in the "askForHelp" form and the "offer-help" form.

**Comment by almereyda** [comment]
Without wanting to be rude, please consider using real geolocations instead of postal codes, only. They are flawed for geodata, and introduce many problems in maintaining the data set in the long run.

https://towardsdatascience.com/stop-using-zip-codes-for-geospatial-analysis-ceacb6e80c38

Please reconsider if this kind of backwards compatibility is needed, or if it wouldn't be better to keep the post code field, but introduce an additional geolocation.

**Comment by Maurice22** [comment]
This is exactly what we are planning to do regarding this issue.

**Comment by Maurice22** [comment]
Is the database migration fully done? If not, I would keep it open or create a new issue.

**Comment by tgraupne** [comment]
> Is the database migration fully done? If not, I would keep it open or create a new issue.

Good point, I am not sure. Could you follow up on that?

**Comment by Maurice22** [comment]
Data migration finished. Closing this issue.
